# This is a basic workflow to help you get started with Actions

name: Docs
on:
  push:
    branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - uses: leafo/gh-actions-lua@v5
    - uses: leafo/gh-actions-luarocks@v2

    - name: install modules
      run: luarocks install ldoc
        
    - name: build the docs
      run: ldoc .
      
    - name: push
      uses: github-actions-x/commit@v2.5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'Auto-update for docs'
        force-add: 'true'
        files: docs/
        name: Juanjo Salvador
        email: juanjosalvador@netc.eu
